### ISSUE TITLE
Enable the usage of `poetry -C root/example_module`

### ISSUE THREAD

**Issue by BillRozy** [ag14774/poetry-monoranger-plugin#80]
Hello!

I am trying to use this plugin to setup monorepository with several independent python libraries.
Some of them have dependencies on other.
Root of the project is not a package, it is just a container for convenient development and documentation.

the structure is like this:
```
- toolbox
- pyproject.toml
  - modules
    - mod1
      - pyproject.toml  
    - mod2
      - pyproject.toml  
    - mod3
      - pyproject.toml   
```

Simplified root pyproject.toml:
```toml
[project]
name = "toolbox"
[tool.poetry]
package-mode = false
[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "."
[tool.poetry.dependencies]
python = ">=3.10,<4.0"
mod1 = { path = "modules/mod1", develop = true }
mod2 = { path = "modules/mod2", develop = true }
mod3 = { path = "modules/mod3", develop = true }
```
Simplified pyproject.toml of some module:
```toml
[project]
version = "1.0.0"
name = "mod2"
[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
mod1 = { path = "../mod1", develop = true }
```

If i use commands like "poetry install" or "poetry lock", everything is fine, i have one .venv created which i can use in development process of all those modules. But how can i build them with pinned version of dependencies?

In documentation of this plugin it is said:
`poetry build`:
Builds the *current* project, replacing editable path dependencies with the current version of the package. This is useful when building a project that depends on another project in the monorepo, as it ensures that the built package can be installed (e.g. as a wheel file) without expecting the other project to be present in a specific location.

What does it mean *current* project? How can i build one of my modules?
Should I use:
```
poetry build -C modules/mod2
or
poetry build -P modules/mod2
```
Is it designed way of building submodules or there is some other command?

Thanks for your help
